### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#1]
### 1. 이 앱을 언제 사용하나요?
개발과 관련한 또는 IT와 관련된 스터디를 찾고 같이 공부하고 소통하고 싶을 때 사용합니다.

### 2. 제약 조건은 무엇인가요?
- 스터디를 주최하고 싶은 사용자는 스터디를 위한 게시글 또는 소개글을 비롯한 방?을 만듭니다.
- 사용자는 자신이 원하는 스터디가 있을 때 참가 신청 기간 동안 참가 신청을 할 수 있습니다.
- 스터디에 참여한 사용자끼리는 채팅을 자유롭게 할 수 있습니다. (시간이 있으면..)

### 3. 구체적인 사례는 무엇인가요?
- 사용자는 로그인을 해야 스터디를 만들거나 참여할 수 있습니다.
- 메인 페이지
    - 스터디 목록이 카테고리 별, 태그 별로 스터디 목록이 조회될 수 있습니다.
- 소개 페이지
    - 참여하고 싶은 사용자는 신청 기간 동안 참가 신청을 한 뒤, 주최하는 사용자는 참가 승인을 해줘야 스터디에 참여할 수 있습니다.
    - [moment.js](https://momentjs.com/)와 [react-momnet](https://www.npmjs.com/package/react-moment)를 사용하여 실시간으로 신청 마감 시간이 얼마나 남았는지 알려줄 수 있습니다. (예를 들어, 1시간 후 마감, 2일 후 마감.) #9 
    - 현재 스터디에 참여 인원과 참여 최대 인원 수를 나타냅니다.
- 스터디 모집 글 작성 페이지
    - 로그인을 해야 작성할 수 있습니다.
    - [draft.js](https://draftjs.org/)와 [react-draft-wysiwyg](https://jpuri.github.io/react-draft-wysiwyg/)를 사용할까 생각중 입니다.
- 내 정보 페이지
    - 현재 내가 참가한 스터디 목록 등을 보여줍니다.
    - 스터디 주최자에게는 참가 신청한 사용자에게 참여 여부를 결정할 수 있습니다.
- 채팅을 통해 스터디원끼리 자유롭게 소통하고 지식을 공유할 수 있습니다. [시간이 되면.]
- 스터디를 찾기 위한 사이트 같은 것들은 [커넥츠](https://www.conects.com/archives/together/study?category_id=85#none), [캠퍼스픽](https://www.campuspick.com/study), [OKKY](https://okky.kr/articles/gathering) 이 정도인거 같습니다.
- 추후 백앤드를 구현할 생각입니다.

### 4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- 일단, 디자인보단 기능 위주로 해보겠습니다.
    - [x] 프로젝트 초기 세팅하기 #2 
    - [x] 홈 화면이 될 스터디 목록 (json-server 사용) 
        - [x] 스터디 목록 보여주기 #3
        - [x] 소개화면으로 이동하게 제목에 Link 설정 #5 
        - [x] 간단하게 CSS 설정해주기 #8 
        - [x] 실시간으로 스터디 모집 상태 보여주게 하기 #9 #10 
        - [x] 태그 클릭시 해당 태그를 가진 스터디 목록만 보여주게 하기 #12 #13
    - [x] 스터디 소개 화면 #5 
        - [x] 간단하게 CSS 설정해주기 #14 
        - [x] 실시간으로 스터디 모집 상태 보여주게 하기 #15 
        - [x] 스터디 신청 상태에 따라 버튼 상태 변경하기 #17

**Comment by hannut91** [comment]
와 ㅎㅎ 스터디를 모집하고 스터디를 할 수 있는 플랫폼이군요 ㅎㅎㅎ

이번주 안에는 스터디를 소개하고 스터디 목록을 확인할 수 있겠네요.

스터디 주제에 따라서 검색도 할 수 있도록 하거나, 대기자 신청 등 다양한 기능들을 확장하면 재밌을 것 같아요. 하지만 이런 것들은 그냥 저의 생각이고 정말 중요한 것을 실제 사용자들의 피드백이 더 중요해요. 일주일 안에 실제로 사용자들에게 보여줄 수 있는 기능들을 보여주고 피드백을 얻어서 그 피드백을 개선하면서 기능을 개선해 보세요 ㅎㅎ

**Comment by saseungmin** [comment]
안그래도 하고 싶은 기능들이 많은데 기간 안에 할 수 있을까? 생각부터 들어서 일단 작게 시작해볼려고 합니다!
추후에 점점 추가해 볼 생각입니다.

**Comment by wholemann** [comment]
윤석님 말씀처럼 무조건 작게 작게 시작하고 가장 핵심인 기능을 최대한 빨리 구현해서 검증하는 게 중요합니다.

일단은 당장 사용할 수 있어야 합니다ㅎㅎ
