### ISSUE TITLE
2주차 진행

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#20]
### 1. 이 앱을 언제 사용하나요?
개발과 관련한 또는 IT와 관련된 스터디를 찾고 같이 공부하고 소통하고 싶을 때 사용합니다.

### 2. 이번 주 구현에 있어서 제약 조건은 무엇인가요?
- 스터디를 주최자가 되어 모집할 수 있게 스터디 소개 글을 작성할 수 있습니다.
- 로그인한 사용자만 참여와 스터디 생성이 가능합니다.

### 3. 이번 주 구체적인 사례는 무엇인가요?
- 사용자는 로그인을 해야 스터디를 만들거나 참여할 수 있습니다.
- 스터디 모집 글 작성 페이지
    - 로그인을 해야 작성할 수 있습니다.
    - [draft.js](https://draftjs.org/)와 [react-draft-wysiwyg](https://jpuri.github.io/react-draft-wysiwyg/)를 사용할까 생각중 입니다.
-  [firebase](https://firebase.google.com/) 사용해서 구현하기. or 백앤드의 MongoDB 사용해서 구현하기.
    - firebase는 사용해본적 x / mongoose를 사용해서 백앤드 구현해본적 O

### 4. 이번 주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- [x] 글 작성 페이지 구현하기
    - [x] 글 작성 페이지 기본 모양 잡기 #22 
    - [x] 태그 작성 기능 추가하기 #23  #24 
    - [x] 스터디 글 등록하기 #25 #26 
    - [x] 스터디 글 등록하면 해당 페이지로 이동 #26
    - [x] 스터디 글 등록 중 취소 버튼 클릭하면 메인페이지로 이동 #28 
    - [x] 에디터 적용하기 #30 
        - [x] 에디터 적용에 따라 소개페이지에 `dangerouslySetInnerHTML` 적용 #34 
- [x] api 통신을 위한 백앤드 기능 구현하기 #32 
    - [x] firestore 사용하기 #32 
- [x] 배포하기 #32 
    - https://sweet-1cfff.web.app/
- [x] 로그인/회원가입 기능 구현
    - [x] 로그인/회원가입 페이지 만들기와 헤더에 로그인 회원가입 링크 생성 #35 
    - [x] 로그인/회원가입 페이지의 input fields에 대한 onChange action설정 #37 
    - [x] 로그인과 회원가입을 구현하기 위해 firebase auth를 사용한다. #38 #40 
    - [x] 회원가입 구현 #38 
    - [x] 로그인 구현 #41  
    - [x] 로그아웃 구현 #42  
    - [x] header 상태 변경하기 (로그인 시 logout 이 보이게) #41 #42 
- [ ] CSS 덧붙이기

**Comment by Kihyun92** [comment]
매우 잘 진행하고 계신 것 같네요 👍  
혹시 진행하면서 도움이 필요하면 편하게 말씀해주세요! 같이 고민해보아요 ☺️
