### ISSUE TITLE
3주차 계획

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#44]
### 🤔 1. 이 앱을 언제 사용하나요?
개발과 관련한 또는 IT와 관련된 스터디를 찾고 같이 공부하고 소통하고 싶을 때 사용합니다.

### 🌈 2. 이번 주 구현에 있어서 제약 조건은 무엇인가요?
회원인 사용자는 스터디에 기간 내에 신청할 수 있습니다.
내 정보? 페이지에서는 내가 신청한 스터디 목록을 확인할 수 있습니다.

### 🎯 3. 이번 주 구체적인 사례는 무엇인가요?
로그인을 하거나 회원이여만 글 작성과 신청이 가능합니다.
내 정보 페이지는 회원만 사용가능합니다.
글 작성시 validation 검사를 해야합니다. 만약 에러가 발생시 에러를 띄웁니다.
로그인 및 회원가입시 validation 검사를 해야합니다. 만약 에러가 발생시 에러를 띄웁니다.
로딩시 로딩 화면이 보입니다. ( [react-content-loader](https://github.com/danilowoz/react-content-loader)를 사용해볼까 생각중입니다.)

### 🚀 4. 이번 주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- [x] react-use의 unmount와 useInterval로 변경하기 #46 #47 
- [x] 글 작성 페이지에 validation 체크하기 [#27] #48 
- [x] 로그인 및 회원가입 페이지에 validation 체크하기 [#27]  #49 #50 
- [x] 현재 글 작성자에 하드코딩으로 사용자를 넣어주는 부분 로그인한 사용자로 변경해주기 [#27] #56 
- [x] 로그인한 사용자는 스터디에 참가 신청할 수 있게 하기, 버튼 상태가 변경되게 하기. #51 
- [x] 이슈 사항 수정 #57 #58 
- [x] 전체적인 CSS 수정 및 덧붙이기
    - [x] 버튼에 대한 CSS 수정 #62  
    - [x] 스터디 목록(메인 화면) CSS 수정 #66 
    - [x] 로그인 회원가입 폼 CSS 수정 #68 
    - [x] 스터디 글 작성 페이지 CSS 적용 #69 
- [x] button과 input에 대한 refactoring 하기 #62 
- [x] 리덕스 부분 refactoring 하기 #60 
- [x] useCallback이나 React.memo 등..을 사용하여 성능 최적화하기 #71 
- [x] 목록 불러올 때 태그가 존재하는 경우에 대한 문제 변경하기 [#13] #59 
- [x] 스터디 목록을 마감일자가 빠른 순으로 정렬 #70 
- [x] 로딩시 화면 구현하기 #72 
- [ ] 내 정보 페이지 구현하기
    - [ ] 내가 접수한 스터디 목록 만들기
    - [ ] 해당 스터디에 대해 채팅 기능 만들기 (시간이 있으면)
