### ISSUE TITLE
수정해야 할 issue 사항.

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#57]
- [x] 회원가입할 때 에러를 반환한 후 `unmount` 될 때 에러 정보를 `clear`를 안해줘서 에러 정보가 그대로 남아있어서 회원가입 성공 후, 로그인 페이지로 이동될 때도 해당 에러 정보가 그대로 로그인 페이지에도 나타난다. #58 
- [x] 글 작성 후 리턴 받은 `groupId` 가 존재하면 `history push`를 해주고, 소개 페이지로 이동 후 `unmount` 할 때, `groupId` 값을 안비워줘서 글을 다시 작성할 때 계속 같은 페이지로 이동되어 글을 더 이상 작성하지 못하는 현상. #58 
- [x] 태그를 작성할 때 엔터를 쳐야지 입력이 되는데 햇갈리는 부분. 삭제할 때도 x 표시같은것을 해줘야할 거 같다. #69
