### ISSUE TITLE
4주차(마지막 주차) 계획

### ISSUE THREAD

**Issue by saseungmin** [CodeSoom/project-react-2-saseungmin#77]
### 🤔 1. 이 앱을 언제 사용하나요?
개발과 관련한 또는 IT와 관련된 스터디를 찾고 같이 공부하고 소통하고 싶을 때 사용합니다.

### 🌈 2. 이번 주 구현에 있어서 제약 조건은 무엇인가요?
- 내 스터디 목록을 확인할 수 있는 페이지를 만들고 싶었지만, 한 주가지고는 절대 못할 거 같다는 판단으로 이 기능은 코드숨 과정이 끝나고 추가적으로 작업할 예정.
- 신청서는 간단하게 모달창으로 작성할 수 있게 할 예정
- 스터디 주최자는 모달창으로 참여 신청한 사용자들을 볼 수 있고 (내 정보에 구현할 예정이였으나 기간내에 구현하기 힘들 거 같다.) 참여 승인을 하거나 참여 거절을 할 수 있다. 

### 🎯 3. 이번 주 구체적인 사례는 무엇인가요?
- 스터디에 참여 신청한 사용자 중에서 신청 기간 동안 취소하고 싶은 사용자는 신청을 취소할 수 있습니다. [#76]
- 신청한 사용자는 스터디의 주최자의 확인을 받아야 완전한 참여가 가능합니다.
- 스터디를 신청할 때 간단한 신청서를 제출할 수 있습니다. 
(왜 스터디에 참여해야 하는지, 어떤 동기부여로 참여를 하는지..등) [#52]

### 🚀 4. 이번 주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- [x] 비 로그인 시 신청 버튼 클릭하면 모달창으로 로그인 후 신청가능하다는 메시지를 띄우는 것으로 변경하기. #79 
- [x] 스터디 목록에 신청 마감일이 몇일 남았는지 보여주는 것으로 변경하기. [#53] #80 
- [x] 스터디에 참여 신청한 사용자는 신청을 취소 할 수 있다. (단, 신청 기간 내에만) #81 
- [x] 신청 취소시 한 번 더 확인을 위해 모달창으로 확인 후 취소 결정  #82 
- [x] 신청할 때 모달창으로 간단한 신청서 작성 모달창 구현하기. #85 #86 #87 #88 
- [x] 주최자가 신청한 사용자를 신청을 승인할 지 취소할 지 결정할 수 있게 모달창으로 구현. (아마 신청자의 신청서도 같이 보이게 하기?) - 너무 커질거 같긴하다.
    - [x] 스터디의 주최자를 위한 '스터디 참여 승인하기' 버튼 생성 #89 
    - [x] 스터디 신청자 목록 모달창 구현 #93 
    - [x] 신청자의 신청서를 볼 수 있게 모달창으로 구현 #95  
    - [x] 주최자는 신청한 신청자들을 신청 승인을 취소 및 승인할 수 있다. #97
    - [x] 신청자가 존재하지 않을때 "신청자가 존재하지 않습니다." #101 
    - [x] 스터디의 주최자가 보는 화면에 미 승인 신청자가 존재할 때 "1명이 승인을 기다리고 있습니다!"와 같은 내용이 보인다. #114
- [x] 모집이 마감되면 주최자의 소개 페이지에는 "스터디를 진행해주세요"가 보인다. #99
- [x] 소개 페이지의 신청 현황 로직 변경 => 승인이 되어야지 참여자의 counter가 올라간다. #100 
- [x] 소개 페이지 리팩토링하기 #90 
- [x] 소개 페이지의 참여를 신청한 신청자 상태 변경하기
    - [x] 신청 후 신청한 사용자는 주최자를 승인을 기달리기 위한 "승인 대기중.." 이 나타난다. #102 
    - [x] 주최자가 승인 후 신청자에겐 "승인 완료"가 보인다. #103 
    - [x] 모집 마감 이후 주최자가 승인을 하지 않은 사용자는 "승인 거절"이 나타난다. #107 
- [x] [react-helmet](https://www.npmjs.com/package/react-helmet)을 사용해서 타이틀 설정하기 #105 
- [x] 글 작성 페이지의 에러 메시지를 세분화시켜서 나타낸다. #106 
- [x] 스터디 목록 수정하기
    - [x] 스터디 목록에 간단하게 내용이 보인다. #109
    - [x] 스터디 목록의 content-loader 수정 #110 
- [x] 제목 적용 #111 
- [x] CSS를 박스 모델끼리 분리하기 위한 refactoring 작업(정렬) #113
